### ISSUE TITLE
Consider accepting OS versions with `v` included

### ISSUE THREAD

**Issue by imrehg** [balena-os/balenahup#218]
Currently the OS versions passed need to have no `v` in front, ie. `2.31.0+rev1`, instead `v2.31.0+rev1`. It is because the way it is used in conjunction with the OS docker repo https://hub.docker.com/r/resin/resinos/tags

Should consider accepting versions with `v` for consistency. Though have to consider whether:

* that would mean different version than the one with `v`
* or normalize the version by keeping in line with the docker repo tags (removing the `v` from the version silently)

**Comment by xginn8** [comment]
We're moving away from DockerHub, so this ticket is no longer relevant. Public apps do not contain the leading `v`.
