### ISSUE TITLE
If HUP fails due to sporadic network failure, progress stays at 50%

### ISSUE THREAD

**Issue by acostach** [balena-os/balenahup#338]
Thus, the user is not able to determine if HUP failed or not, if it's still ongoing, etc.

Logs available in internal discussion https://www.flowdock.com/app/rulemotion/s-sales/threads/vdPYedOWjh1_Fd8aR5LYPlFzlCc
--- logs form April 2, 9, 13, issue 1).

**Comment by xginn8** [comment]
this has been deployed to production
