### ISSUE TITLE
Remove REC files from boot partition before triggering update

### ISSUE THREAD

**Issue by alexgg** [balena-os/balenahup#373]
REC files are created on the vfat boot partition when it is recovered using fsck- for example after the power is cut while writing to a file on it. These may accumulate and fill the boot partition making hostOS update impossible.

We will remove (and list them in a warning in the host update log file) these *REC files so that they don't prevent a hostOS update.

**Comment by pmirabel** [comment]
Sorry if this is not the right place, 
 am encountering this issue at work, and I just wanted to add that upgrade script is not detecting such errors and output a pretty
`Updating device_uuid succeeded.`
Thanks for dealing with this !

**Comment by jaomaloy** [comment]
> Sorry if this is not the right place, am encountering this issue at work, and I just wanted to add that upgrade script is not detecting such errors and output a pretty `Updating device_uuid succeeded.` Thanks for dealing with this !

Hi @pmirabel , could you create an issue and also give more detail to the problem? for example: what upgrade script do you specifically mean? We can continue from there. Thanks!
